name: Test droid-legacy manifest

on:
  push:
    branches: [ lineage-19.1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core python3-pip wget
          wget https://storage.googleapis.com/git-repo-downloads/repo && sudo mv repo /usr/bin/repo && sudo chmod a+x /usr/bin/repo
      - name: Initialize and sync repos
        run: |
          repo init -u https://github.com/droid-legacy/android.git -b lineage-19.1
          timeout 1m repo sync || true
        timeout-minutes: 6
